// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEjCUipOpXaoNlHipEO_uuf207cOjpH3w',
    appId: '1:500891405739:web:36194706a6c833e00616ee',
    messagingSenderId: '500891405739',
    projectId: 'pyrcamp-app-demo',
    authDomain: 'pyrcamp-app-demo.firebaseapp.com',
    storageBucket: 'pyrcamp-app-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRt_vjrW8u6xLI7WDbFtmwXuGY3bjmQhk',
    appId: '1:500891405739:android:1ac67032851569510616ee',
    messagingSenderId: '500891405739',
    projectId: 'pyrcamp-app-demo',
    storageBucket: 'pyrcamp-app-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxc4CloFHkTymwgJFVQbRKaLQ3jH8gsdU',
    appId: '1:500891405739:ios:4c882ac60d3775520616ee',
    messagingSenderId: '500891405739',
    projectId: 'pyrcamp-app-demo',
    storageBucket: 'pyrcamp-app-demo.appspot.com',
    iosBundleId: 'com.example.pyrcampApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxc4CloFHkTymwgJFVQbRKaLQ3jH8gsdU',
    appId: '1:500891405739:ios:4c882ac60d3775520616ee',
    messagingSenderId: '500891405739',
    projectId: 'pyrcamp-app-demo',
    storageBucket: 'pyrcamp-app-demo.appspot.com',
    iosBundleId: 'com.example.pyrcampApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEjCUipOpXaoNlHipEO_uuf207cOjpH3w',
    appId: '1:500891405739:web:6e5bb877d6afd6ba0616ee',
    messagingSenderId: '500891405739',
    projectId: 'pyrcamp-app-demo',
    authDomain: 'pyrcamp-app-demo.firebaseapp.com',
    storageBucket: 'pyrcamp-app-demo.appspot.com',
  );

}